# Generated by Django 4.0.6 on 2022-07-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tix',
            name='status',
            field=models.CharField(choices=[('W', 'Want to go'), ('P', 'Tix Purchased'), ('G', 'Went to Show')], default='W', max_length=1),
        ),
    ]
